package paper.pss.exp.jfreeChart_project.model;

import java.awt.geom.Line2D;

/**
 * TestCase.java
 *
 * This file defines the data model for test cases used in the createLineRegion
 * function testing.
 * In the metamorphic testing framework, instances of this class represent:
 * 1. Test data generated by test generators
 * 2. Source and follow-up test cases in metamorphic testing
 * 3. Input for the TestRunner engine
 *
 * Each test case contains:
 * - A Line2D object representing the line segment
 * - A width parameter for the line region
 * - A partition ID indicating which input domain partition the test belongs to
 * 
 * Partitions for createLineRegion function:
 * 1: Horizontal line segment (y1 == y2)
 * 2: Vertical line segment (x1 == x2)
 * 3: Diagonal line with positive slope ((y2 > y1 && x2 > x1) || (y2 < y1 && x2
 * < x1))
 * 4: Diagonal line with negative slope ((y2 > y1 && x2 < x1) || (y2 < y1 && x2
 * > x1))
 */
public class TestCase {
    private final Line2D line;
    private final float width;
    private final int partitionId;

    /**
     * Creates a test case with specified Line2D, width and partition ID
     *
     * @param line        The line segment
     * @param width       The width parameter
     * @param partitionId The partition ID of the test case
     */
    public TestCase(Line2D line, float width, int partitionId) {
        this.line = line;
        this.width = width;
        this.partitionId = partitionId;
    }

    /**
     * Gets the line segment
     *
     * @return The line segment
     */
    public Line2D getLine() {
        return line;
    }

    /**
     * Gets the width parameter
     *
     * @return The width parameter
     */
    public float getWidth() {
        return width;
    }

    /**
     * Gets the partition ID of this test case
     *
     * @return The partition ID
     */
    public int getPartitionId() {
        return partitionId;
    }

    /**
     * Returns a string representation of this test case
     */
    @Override
    public String toString() {
        return String.format("Partition %d: createLineRegion(Line2D[(%f,%f)-(%f,%f)], %f)",
                partitionId,
                line.getX1(), line.getY1(),
                line.getX2(), line.getY2(),
                width);
    }
}