package paper.pss.exp.lang_project.model;

import java.util.Calendar;
import java.util.Date;

/**
 * TestCase.java
 * 
 * This file defines the data model for test cases used in the isSameDay
 * function testing.
 * In the mutation testing framework, instances of this class represent:
 * 1. Test data generated by PartitionTestGenerator and RandomTestGenerator
 * 2. Source and follow-up test cases in metamorphic testing
 * 3. Input for the TestRunner engine
 * 
 * Each test case contains:
 * - Two date parameters (which can be null) as input to isSameDay
 * - Two calendar parameters (which can be null) as input to isSameDay
 * - A partition ID indicating which input domain partition the test belongs to
 * 
 * Partition ID meanings:
 * 1: Null inputs - At least one parameter is null
 * 2: Identical dates - Year, month, day are all the same
 * 3: Same year/month, different day
 * 4: Same year/day, different month
 * 5: Same month/day, different year
 * 6: Same year, different month and day
 * 7: Same month, different year and day
 * 8: Same day, different year and month
 * 9: All different - Year, month, day all differ
 * 
 * For randomly generated test cases, partition ID might be 0 (unclassified)
 */
public class TestCase {
    private final Date date1;
    private final Date date2;
    private final Calendar cal1;
    private final Calendar cal2;
    public final int partitionId;

    /**
     * Creates a test case with Date parameters
     * 
     * @param date1       The first date parameter
     * @param date2       The second date parameter
     * @param partitionId The partition ID of the test case
     */
    public TestCase(Date date1, Date date2, int partitionId) {
        this.date1 = date1;
        this.date2 = date2;

        // Create corresponding Calendar objects for the Date objects
        this.cal1 = date1 != null ? Calendar.getInstance() : null;
        if (cal1 != null) {
            cal1.setTime(date1);
        }

        this.cal2 = date2 != null ? Calendar.getInstance() : null;
        if (cal2 != null) {
            cal2.setTime(date2);
        }

        this.partitionId = partitionId;
    }

    /**
     * Creates a test case with Calendar parameters
     * 
     * @param cal1        The first calendar parameter
     * @param cal2        The second calendar parameter
     * @param partitionId The partition ID of the test case
     */
    public TestCase(Calendar cal1, Calendar cal2, int partitionId) {
        this.cal1 = cal1;
        this.cal2 = cal2;

        // Create corresponding Date objects for the Calendar objects
        this.date1 = cal1 != null ? cal1.getTime() : null;
        this.date2 = cal2 != null ? cal2.getTime() : null;

        this.partitionId = partitionId;
    }

    /**
     * Gets the first date parameter
     * 
     * @return The first date
     */
    public Date getDate1() {
        return date1;
    }

    /**
     * Gets the second date parameter
     * 
     * @return The second date
     */
    public Date getDate2() {
        return date2;
    }

    /**
     * Gets the first calendar parameter
     * 
     * @return The first calendar
     */
    public Calendar getCalendar1() {
        return cal1;
    }

    /**
     * Gets the second calendar parameter
     * 
     * @return The second calendar
     */
    public Calendar getCalendar2() {
        return cal2;
    }

    /**
     * Gets the partition ID of this test case
     * 
     * @return The partition ID
     */
    public int getPartitionId() {
        return partitionId;
    }

    /**
     * Formats a date object as a concise string representation
     * 
     * @param date The date to format
     * @return The formatted string
     */
    private String formatDate(Date date) {
        if (date == null) {
            return "null";
        }

        Calendar cal = Calendar.getInstance();
        cal.setTime(date);

        return String.format("Date(%d, %d, %d, %d, %d)",
                cal.get(Calendar.YEAR),
                cal.get(Calendar.MONTH),
                cal.get(Calendar.DAY_OF_MONTH),
                cal.get(Calendar.HOUR_OF_DAY),
                cal.get(Calendar.MINUTE));
    }

    /**
     * Formats a calendar object as a concise string representation
     * 
     * @param cal The calendar to format
     * @return The formatted string
     */
    private String formatCalendar(Calendar cal) {
        if (cal == null) {
            return "null";
        }

        return String.format("Calendar(%d, %d, %d, %d, %d)",
                cal.get(Calendar.YEAR),
                cal.get(Calendar.MONTH),
                cal.get(Calendar.DAY_OF_MONTH),
                cal.get(Calendar.HOUR_OF_DAY),
                cal.get(Calendar.MINUTE));
    }

    @Override
    public String toString() {
        String date1Str = formatDate(date1);
        String date2Str = formatDate(date2);

        return String.format("Partition %d: isSameDay(%s, %s)",
                partitionId,
                date1Str,
                date2Str);
    }

    /**
     * Returns a string representation of this test case with calendar parameters
     * 
     * @return The string representation with calendar parameters
     */
    public String toCalendarString() {
        String cal1Str = formatCalendar(cal1);
        String cal2Str = formatCalendar(cal2);

        return String.format("Partition %d: isSameDay(%s, %s)",
                partitionId,
                cal1Str,
                cal2Str);
    }
}