package paper.pss.exp.jackson_project.model;

/**
 * TestCase.java
 *
 * This file defines the data model for test cases used in the parseInt function
 * testing.
 * In the metamorphic testing framework, instances of this class represent:
 * 1. Test data generated by test generators
 * 2. Source and follow-up test cases in metamorphic testing
 * 3. Input for the TestRunner engine
 *
 * Each test case contains:
 * - An input string parameter to parseInt
 * - A partition ID indicating which input domain partition the test belongs to
 */
public class TestCase {
    private final String inputString;
    public final int partitionId;

    /**
     * Creates a test case with a string parameter and partition ID
     *
     * @param inputString The string to be parsed
     * @param partitionId The partition ID of the test case
     */
    public TestCase(String inputString, Integer partitionId) {
        this.inputString = inputString;
        this.partitionId = (partitionId != null) ? partitionId : determinePartition(inputString);
    }

    /**
     * Determines the partition ID (1 to 6) for a given input string.
     *
     * Partition definitions:
     * 1: Positive, 1–2 digits
     * 2: Positive, 3–8 digits
     * 3: Positive, exactly 9 digits
     * 4: Negative, 2–3 characters (including minus sign)
     * 5: Negative, 4–10 characters (including minus sign)
     * 6: Negative, exactly 10 characters (including minus sign)
     *
     * @param s The input string to classify (e.g., "123", "-42")
     * @return Partition ID (1 to 6)
     */
    public static int determinePartition(String s) {
        if (s == null || s.isEmpty()) {
            throw new IllegalArgumentException("Input string cannot be null or empty");
        }

        if (s.startsWith("-")) {
            int length = s.length();
            if (length <= 3) {
                return 4; // Partition 4: Negative, 2–3 characters
            } else if (length <= 10) {
                return 5; // Partition 5: Negative, 4–10 characters
            } else {
                return 6; // Partition 6: Negative, exactly 10 characters or more
            }
        } else {
            int length = s.length();
            if (length <= 2) {
                return 1; // Partition 1: Positive, 1–2 digits
            } else if (length <= 8) {
                return 2; // Partition 2: Positive, 3–8 digits
            } else {
                return 3; // Partition 3: Positive, exactly 9 digits or more
            }
        }
    }

    /**
     * Gets the input string parameter
     *
     * @return The input string to be parsed
     */
    public String getInput() {
        return inputString;
    }

    /**
     * Gets the partition ID of this test case
     *
     * @return The partition ID
     */
    public int getPartitionId() {
        return partitionId;
    }

    /**
     * Returns a string representation of this test case
     */
    @Override
    public String toString() {
        return String.format("Partition %d: parseInt(\"%s\")",
                partitionId,
                inputString);
    }

    public static void main(String[] args) {
        // Test cases with expected partition IDs
        String[] inputs = {
            "0",              // 1
            "42",             // 1
            "123",            // 2
            "12345678",       // 2
            "123456789",      // 3
            "123456789012",   // 3

            "-0",             // 4
            "-42",            // 4
            "-123",           // 5
            "-12345678",      // 5
            "-1234567890",    // 6
            "-123456789012"   // 6
        };

        int[] expectedPartitions = {
            1, 1, 2, 2, 3, 3,
            4, 4, 5, 5, 6, 6
        };

        System.out.println("=== Functional Tests ===");
        for (int i = 0; i < inputs.length; i++) {
            String input = inputs[i];
            int expected = expectedPartitions[i];
            int actual = TestCase.determinePartition(input);

            TestCase tc = new TestCase(input, actual);

            // Output and validation
            System.out.println("Input: \"" + input + "\"");
            System.out.println("  Expected Partition: " + expected);
            System.out.println("  Actual Partition:   " + actual);
            System.out.println("  getInputString():   " + tc.getInput());
            System.out.println("  getPartitionId():   " + tc.getPartitionId());
            System.out.println("  toString():         " + tc.toString());
            System.out.println("  Test Result:        " + (actual == expected ? "PASS" : "FAIL"));
            System.out.println();
        }

        // Edge Case: Empty string
        System.out.println("=== Edge Case: Empty String ===");
        try {
            TestCase.determinePartition("");
            System.out.println("FAIL: Expected exception not thrown for empty string.");
        } catch (IllegalArgumentException e) {
            System.out.println("PASS: Caught expected exception - " + e.getMessage());
        }

        // Edge Case: Null string
        System.out.println("=== Edge Case: Null String ===");
        try {
            TestCase.determinePartition(null);
            System.out.println("FAIL: Expected exception not thrown for null input.");
        } catch (IllegalArgumentException e) {
            System.out.println("PASS: Caught expected exception - " + e.getMessage());
        }
    }
}